import requests

account_id = 929
cluster_id = 34797
headers = {"Authorization": f"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIzOGEwYjJmIn0.eyJzdWIiOiI5OTQyNjYxOS0wYzc3LTQzOGYtYWRhMS1mMjkwOGM2MWU5MGMiLCJ0eXBlIjoidXNlckFjY2Vzc1Rva2VuIiwidGVuYW50SWQiOiIyMzIyZDI2MC03NDg1LTQ5ZDAtOWMxYi02ZTk2YjE2ZWMzYzciLCJ1c2VySWQiOiI3ZDNlODc2YS0yMmEwLTRjNTctOTYzZS04YWNmMzhhMGMyMTciLCJhcHBsaWNhdGlvbklkIjoiYzEyOTdkY2ItODdjYi00NWEyLWI4OTItNzU3MzQ0YTQxMWMyIiwicm9sZXMiOlsiRkVUQ0gtUk9MRVMtQlktQVBJIl0sInBlcm1pc3Npb25zIjpbIkZFVENILVBFUk1JU1NJT05TLUJZLUFQSSJdLCJhdWQiOiIyMzhhMGIyZi0zNmVhLTRhZDgtODFkNy1lYWZkNWY1ZGY5M2IiLCJpc3MiOiJodHRwczovL2F1dGguY2xvdWQuc2N5bGxhZGIuY29tIiwiaWF0IjoxNzQ1Mzk4MjYzfQ.6MP8ss2o3EMH0Ipfbvvwnv39iVO57gsigvfhl4JbH1-DlOzYqPuz1mTmss8DKikT9qT0uE6ImBC2fyk5jraZcjbq_UKRWYPeCOdZZvN3fzdVo5MM9j8ZnvL_eYSPjQisIfUq-CLEYdg3h9wQybKAhxCU36JKAJGXmujKwyxoYnhIgY8gNnxGHHNc4JmQ6yaYIaH6MTFE-XV45C5alj1qNKMM8rnjuLipC43sRvrFLXaEc66XPkpfQm1nnocUavrOLTeW37um8fjKUGx291k89V9gHLsUgpTPYNJ5D0-n4jIsUnjcRERlD8_SwU-G6UcMQFH0jWxgF3jVciE5WJlr1Q"}

url = f"https://api.cloud.scylladb.com/api/v1/accounts/self/clusters/{cluster_id}/auth/cql"

response = requests.get(url, headers=headers)
response.raise_for_status()
auth = response.json()["data"]

cql_username = auth["username"]
cql_password = auth["password"]

print(f"User: {cql_username} & Password: {cql_password}")
