variable "scylla_api_token" {}
variable "cloud" {}
variable "scylla_cluster_name" {}
variable "scylla_version" {}
variable "region" {}
variable "scylla_CIDR" {}
variable "nodes" {}
variable "node_type" {}
variable "scale_nodes" {}
variable "scale_node_type" {}
variable "path_to_key" {}
variable "path_to_private_key" {}
