variable "cloud" {}
variable "scylla_version" {}
variable "scylla_cidr" {}
variable "loader_vpc_region" {}
variable "loader_vpc" {}
variable "loaders" {}
variable "loaders_type" {}
variable "key_name" {}
variable "path_to_key" {}
variable "path_to_private_key" {}
